export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'

export const FETCH_BOOK_REQUEST = 'FETCH_BOOK_REQUEST'
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS'
export const FETCH_BOOK_FAILURE = 'FETCH_BOOK_FAILURE'


export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST'
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS'
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE'


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const USER_IS_LOGEDIN = 'USER_IS_LOGEDIN'

export const FETCH_ORDERHISTORY_REQUEST = 'FETCH_ORDERHISTORY_REQUEST'
export const FETCH_ORDERHISTORY_SUCCESS = 'FETCH_ORDERHISTORY_SUCCESS'
export const FETCH_ORDERHISTORY_FAILURE = 'FETCH_ORDERHISTORY_FAILURE'